version: "3"
services:
  webserver:
    build: 
      context: ./docker/${ARCH}/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    restart: 'always'
    #network_mode: 'host'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-80}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT-443}:443"
      - 8001:8001 #WebSocket port
    depends_on:
      - database
    volumes: 
      - ${DOCUMENT_ROOT-.app/www}:/var/www
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - "./config/supervisor.conf:/etc/supervisor.conf"
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST : ${MYSQL_HOST}
      TZ: ${TZ}
  database:
    build:
      context: "./docker/${ARCH}/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${MYSQL_CONF_DIR-./config/mysql}:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
  db-backup:
    container_name: '${COMPOSE_PROJECT_NAME}-db-backup'
    image: tiredofit/db-backup
    links:
     - database
    volumes:
      - ./app/backup:/backup
      - ./config/backup.sh:/assets/custom-scripts/post-script.sh
    environment:
      DB_TYPE: ${DATABASE}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_DUMP_FREQ: 1440
      DB_DUMP_BEGIN: 0180
      DB_CLEANUP_TIME: 8640
      MD5: FALSE
      COMPRESSION: GZ
      SPLIT_DB: FALSE
      TZ: ${TZ}
    restart: always
  phpmyadmin:
    build:
      context: "./docker/${ARCH}/pma"
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    depends_on:
      - database
      - webserver
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - '${HOST_MACHINE_PMA_PORT-8080}:80'
    volumes: 
      #- /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
      
  # Additional services
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: '${COMPOSE_PROJECT_NAME}-mosquitto'
    volumes:
      - ./config/mosquitto:/mosquitto/config
    network_mode: 'host'
    environment:
      TZ: ${TZ}
    restart: always
  zigbee2mqtt:
    container_name: '${COMPOSE_PROJECT_NAME}-zigbee2mqtt'
    image: koenkk/zigbee2mqtt
    volumes:
      - ./app/zigbee2mqtt/data:/app/data
      - ./app/zigbee2mqtt/run/udev:/run/udev:ro
    restart: always
    network_mode: 'host'
    privileged: true
    environment:
      TZ: ${TZ}